name: Release System Build

on:
  push:
    tags:
      - 'v*'   # Triggers on version tags like v1.2.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: Add build steps if needed
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build system
      #   run: npm run build

      - name: Create system zip
        run: |
          mkdir build
          cp -r * build/
          cd build
          zip -r ../daggerheart-system.zip ./
          cd ..

      - name: Check system.json included
        run: unzip -l daggerheart-system.zip | grep system.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            daggerheart-system.zip
            system.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
