name: Release System Build

on:
  push:
    tags:
      - 'v*'


permissions:
  contents: write


jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update manifest and url in system.json
        run: |
          node scripts/bump-manifest.js
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      # Optional: Build step here

      - name: Create system zip
        run: |
          mkdir build
          shopt -s extglob
          cp -r !(build) build/
          cd build
          zip -r ../daggerheart-system.zip ./
          cd ..


      - name: Check system.json included
        run: unzip -l daggerheart-system.zip | grep system.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            daggerheart-system.zip
            system.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
